name: Test HTML Files on Main

on:
  push:
    branches: [ main ]
    paths: [ '**.html' ]

jobs:
  test-html:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Find HTML files
      id: find-html
      run: |
        HTML_FILES=$(find . -name "*.html" -type f)
        echo "Found HTML files:"
        echo "$HTML_FILES"
        echo "html_files=$HTML_FILES" >> $GITHUB_OUTPUT
        
    - name: Run HTML tests
      run: |
        if [ -n "${{ steps.find-html.outputs.html_files }}" ]; then
          echo "Running tests on HTML files..."
          # Add your HTML test commands here
          # Example: npm test
          # Example: python -m pytest test_html.py
          echo "HTML tests completed"
        else
          echo "No HTML files found to test"
        fi